services:
  spraed.user.repository:
    alias: spraed.user.repository.doctrine

  spraed.user.repository.doctrine:
    class: Spraed\CommandUserBundle\Repository\User\DoctrineUserRepository
    factory_service: doctrine.orm.entity_manager
    factory_method: getRepository
    arguments: [Spraed\CommandUserBundle:User\User]
    public: false